/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type AnonymousFactory = __
/**
 * Anonymous traversal factory.
 *
 * Creates traversal fragments for use in branch/filter steps.
 * The `__` namespace mirrors the Gremlin `__` class.
 */
export declare class __ { }
export type JsGraph = Graph
/**
 * A high-performance graph database.
 *
 * Supports both in-memory and persistent (disk-backed) storage modes.
 *
 * @example
 * ```javascript
 * const { Graph } = require('@interstellar/node');
 *
 * // Create an in-memory graph (fast, non-persistent)
 * const memGraph = Graph.inMemory();
 *
 * // Open a persistent graph (data survives restarts)
 * const diskGraph = Graph.open('./my_graph.db');
 *
 * // Both use the same API
 * const alice = memGraph.addVertex('person', { name: 'Alice', age: 30n });
 * const bob = memGraph.addVertex('person', { name: 'Bob', age: 25n });
 * memGraph.addEdge(alice, bob, 'knows', { since: 2020n });
 * ```
 */
export declare class Graph {
  /**
   * Create a new empty in-memory graph.
   *
   * This is a convenience constructor equivalent to `Graph.inMemory()`.
   */
  constructor()
  /**
   * Create a new empty in-memory graph.
   *
   * In-memory graphs are fast but data is lost when the process exits.
   *
   * @returns A new in-memory Graph instance
   *
   * @example
   * ```javascript
   * const graph = Graph.inMemory();
   * graph.addVertex('person', { name: 'Alice' });
   * // Data is lost when process exits
   * ```
   */
  static inMemory(): JsGraph
  /**
   * Open or create a persistent graph database at the given path.
   *
   * Persistent graphs use memory-mapped files for efficient storage.
   * Data survives process restarts.
   *
   * @param path - Path to the database file
   * @returns A new persistent Graph instance
   *
   * @example
   * ```javascript
   * const graph = Graph.open('./my_graph.db');
   * graph.addVertex('person', { name: 'Alice' });
   * // Data is automatically persisted to disk
   * ```
   */
  static open(path: string): JsGraph
  /**
   * Check if this graph is persistent (disk-backed).
   *
   * @returns true if persistent, false if in-memory
   */
  get isPersistent(): boolean
  /**
   * Add a vertex with a label and optional properties.
   *
   * @param label - The vertex label (e.g., 'person', 'product')
   * @param properties - Optional key-value properties
   * @returns The new vertex's ID as a bigint
   */
  addVertex(label: string, properties?: object | undefined | null): bigint
  /**
   * Get a vertex by ID.
   *
   * @param id - The vertex ID
   * @returns The vertex object, or undefined if not found
   */
  getVertex(id: unknown): object | null
  /**
   * Remove a vertex and all its incident edges.
   *
   * @param id - The vertex ID to remove
   * @returns true if removed, false if not found
   */
  removeVertex(id: unknown): boolean
  /**
   * Set a property on a vertex.
   *
   * @param id - The vertex ID
   * @param key - Property name
   * @param value - Property value
   */
  setVertexProperty(id: unknown, key: string, value: unknown): void
  /**
   * Add an edge between two vertices.
   *
   * @param from - Source vertex ID
   * @param to - Target vertex ID
   * @param label - The edge label (e.g., 'knows', 'purchased')
   * @param properties - Optional key-value properties
   * @returns The new edge's ID as a bigint
   */
  addEdge(from: unknown, to: unknown, label: string, properties?: object | undefined | null): bigint
  /**
   * Get an edge by ID.
   *
   * @param id - The edge ID
   * @returns The edge object, or undefined if not found
   */
  getEdge(id: unknown): object | null
  /**
   * Remove an edge.
   *
   * @param id - The edge ID to remove
   * @returns true if removed, false if not found
   */
  removeEdge(id: unknown): boolean
  /**
   * Set a property on an edge.
   *
   * @param id - The edge ID
   * @param key - Property name
   * @param value - Property value
   */
  setEdgeProperty(id: unknown, key: string, value: unknown): void
  /** Get the total number of vertices. */
  get vertexCount(): number
  /** Get the total number of edges. */
  get edgeCount(): number
  /** Get the current version/transaction ID. */
  get version(): bigint
  /**
   * Start a traversal from all vertices, or specific vertices by ID.
   *
   * @param ids - Optional vertex IDs to start from (single ID or array)
   * @returns A new traversal starting from all vertices or specific vertices
   *
   * @example
   * ```javascript
   * // All vertices
   * const names = graph.V()
   *     .hasLabel('person')
   *     .values('name')
   *     .toList();
   *
   * // Specific vertices
   * const alice = graph.V(aliceId).values('name').first();
   * ```
   */
  V(ids?: unknown | undefined | null): JsTraversal
  /**
   * Start a traversal from all edges, or specific edges by ID.
   *
   * @param ids - Optional edge IDs to start from (single ID or array)
   */
  E(ids?: unknown | undefined | null): JsTraversal
}
export type JsPredicate = Predicate
/**
 * Internal representation of a predicate that can be used in traversal steps.
 *
 * This wraps a boxed Rust predicate for use with napi-rs.
 */
export declare class Predicate { }
/**
 * Predicate factory functions.
 *
 * @example
 * ```typescript
 * import { Graph, P } from '@interstellar/node';
 *
 * graph.V()
 *     .hasWhere('age', P.gte(18))
 *     .hasWhere('name', P.startingWith('A'))
 *     .toList();
 * ```
 */
export declare class P {
  /**
   * Equals comparison.
   *
   * @param value - Value to compare against
   */
  static eq(value: unknown): Predicate
  /**
   * Not equals comparison.
   *
   * @param value - Value to compare against
   */
  static neq(value: unknown): Predicate
  /**
   * Less than comparison.
   *
   * @param value - Value to compare against
   */
  static lt(value: unknown): Predicate
  /**
   * Less than or equal comparison.
   *
   * @param value - Value to compare against
   */
  static lte(value: unknown): Predicate
  /**
   * Greater than comparison.
   *
   * @param value - Value to compare against
   */
  static gt(value: unknown): Predicate
  /**
   * Greater than or equal comparison.
   *
   * @param value - Value to compare against
   */
  static gte(value: unknown): Predicate
  /**
   * Value is between start and end (inclusive start, exclusive end).
   *
   * @param start - Range start
   * @param end - Range end
   */
  static between(start: unknown, end: unknown): Predicate
  /**
   * Value is strictly inside range (exclusive).
   *
   * @param start - Range start
   * @param end - Range end
   */
  static inside(start: unknown, end: unknown): Predicate
  /**
   * Value is outside range.
   *
   * @param start - Range start
   * @param end - Range end
   */
  static outside(start: unknown, end: unknown): Predicate
  /**
   * Value is within the given set.
   *
   * @param values - Array of values to check membership
   */
  static within(values: unknown): Predicate
  /**
   * Value is NOT within the given set.
   *
   * @param values - Array of values to exclude
   */
  static without(values: unknown): Predicate
  /**
   * String contains substring.
   *
   * @param substring - Substring to find
   */
  static containing(substring: string): Predicate
  /**
   * String does NOT contain substring.
   *
   * @param substring - Substring that must be absent
   */
  static notContaining(substring: string): Predicate
  /**
   * String starts with prefix.
   *
   * @param prefix - Required prefix
   */
  static startingWith(prefix: string): Predicate
  /**
   * String does NOT start with prefix.
   *
   * @param prefix - Forbidden prefix
   */
  static notStartingWith(prefix: string): Predicate
  /**
   * String ends with suffix.
   *
   * @param suffix - Required suffix
   */
  static endingWith(suffix: string): Predicate
  /**
   * String does NOT end with suffix.
   *
   * @param suffix - Forbidden suffix
   */
  static notEndingWith(suffix: string): Predicate
  /**
   * String matches regular expression.
   *
   * @param pattern - Regex pattern
   */
  static regex(pattern: string): Predicate
  /**
   * Logical AND of two predicates.
   *
   * @param p1 - First predicate
   * @param p2 - Second predicate
   */
  static and(p1: Predicate, p2: Predicate): Predicate
  /**
   * Logical OR of two predicates.
   *
   * @param p1 - First predicate
   * @param p2 - Second predicate
   */
  static or(p1: Predicate, p2: Predicate): Predicate
  /**
   * Logical NOT of a predicate.
   *
   * @param p - Predicate to negate
   */
  static not(pred: Predicate): Predicate
  /**
   * Test if a geometry is within a given distance of a point.
   *
   * @param lon - Longitude of center point
   * @param lat - Latitude of center point
   * @param distanceKm - Radius in kilometers
   *
   * @example
   * ```javascript
   * graph.V()
   *     .hasWhere('location', P.withinDistance(-122.4, 37.7, 5.0))
   *     .values('name')
   *     .toList();
   * ```
   */
  static withinDistance(lon: number, lat: number, distanceKm: number): Predicate
}
export type JsTextQuery = TextQuery
/**
 * A structured text search query.
 *
 * Use the `TextQ` factory to create instances.
 */
export declare class TextQuery { }
/**
 * Factory for creating structured text search queries.
 *
 * @example
 * ```javascript
 * import { Graph, TextQ } from '@interstellar/node';
 *
 * // Simple match query
 * graph.searchTextQueryV('description', TextQ.match('graph database'), 10);
 *
 * // Phrase query
 * graph.searchTextQueryV('description', TextQ.phrase('graph database', 0), 10);
 *
 * // Boolean AND
 * graph.searchTextQueryV('description', TextQ.and([
 *     TextQ.match('graph'),
 *     TextQ.match('database'),
 * ]), 10);
 * ```
 */
export declare class TextQ {
  /**
   * Free-text match query (OR of terms by default).
   *
   * @param text - Search text
   */
  static match(text: string): TextQuery
  /**
   * All terms must match (AND of terms).
   *
   * @param text - Search text
   */
  static matchAll(text: string): TextQuery
  /**
   * Phrase query: terms must appear in order.
   *
   * @param text - Phrase text
   * @param slop - Positional slop (0 = strict adjacency)
   */
  static phrase(text: string, slop?: number | undefined | null): TextQuery
  /**
   * Prefix match on a single term.
   *
   * @param prefix - Term prefix
   */
  static prefix(prefix: string): TextQuery
  /**
   * Boolean AND: all subqueries must match.
   *
   * @param queries - Array of TextQuery objects
   */
  static and(queries: Array<TextQuery>): TextQuery
  /**
   * Boolean OR: any subquery can match.
   *
   * @param queries - Array of TextQuery objects
   */
  static or(queries: Array<TextQuery>): TextQuery
  /**
   * Boolean NOT: negate a query.
   *
   * Must be combined with a positive clause at the top level.
   *
   * @param query - Query to negate
   */
  static not(query: TextQuery): TextQuery
}
export type JsTraversal = Traversal
/**
 * A graph traversal that can be chained with various steps.
 *
 * Traversals are lazy - they only execute when a terminal step is called.
 */
export declare class Traversal {
  /**
   * Create a new empty traversal (internal use only).
   *
   * This constructor is not meant to be called from JavaScript directly.
   * Use graph.V() or graph.E() to create traversals.
   */
  constructor()
  /**
   * Filter to elements with a specific label.
   *
   * @param label - The label to match
   */
  hasLabel(label: string): Traversal
  /**
   * Filter to elements with any of the specified labels.
   *
   * @param labels - Array of labels to match (OR logic)
   */
  hasLabelAny(labels?: unknown | undefined | null): Traversal
  /**
   * Filter to elements that have a property (any value).
   *
   * @param key - Property name
   */
  has(key: string): Traversal
  /**
   * Filter to elements that have a property with a specific value.
   *
   * @param key - Property name
   * @param value - Exact value to match
   */
  hasValue(key: string, value: unknown): Traversal
  /**
   * Filter to elements where property matches a predicate.
   *
   * @param key - Property name
   * @param predicate - Predicate to test (e.g., P.gt(10))
   */
  hasWhere(key: string, predicate: Predicate): Traversal
  /**
   * Filter to elements that do NOT have a property.
   *
   * @param key - Property name that must be absent
   */
  hasNot(key: string): Traversal
  /**
   * Filter to elements with specific IDs.
   *
   * @param ids - Element IDs to match
   */
  hasId(ids: unknown): Traversal
  /** Remove duplicate elements from the traversal. */
  dedup(): Traversal
  /**
   * Limit results to the first n elements.
   *
   * @param n - Maximum number of elements
   */
  limit(n: number): Traversal
  /**
   * Skip the first n elements.
   *
   * @param n - Number of elements to skip
   */
  skip(n: number): Traversal
  /**
   * Take elements in a range [start, end).
   *
   * @param start - Start index (inclusive)
   * @param end - End index (exclusive)
   */
  range(start: number, end: number): Traversal
  /**
   * Navigate to outgoing adjacent vertices.
   *
   * @param labels - Optional edge labels to traverse
   */
  out(labels?: unknown | undefined | null): Traversal
  /**
   * Navigate to incoming adjacent vertices.
   *
   * @param labels - Optional edge labels to traverse
   */
  in(labels?: unknown | undefined | null): Traversal
  /**
   * Navigate to adjacent vertices in both directions.
   *
   * @param labels - Optional edge labels to traverse
   */
  both(labels?: unknown | undefined | null): Traversal
  /**
   * Navigate to outgoing edges.
   *
   * @param labels - Optional edge labels to match
   */
  outE(labels?: unknown | undefined | null): Traversal
  /**
   * Navigate to incoming edges.
   *
   * @param labels - Optional edge labels to match
   */
  inE(labels?: unknown | undefined | null): Traversal
  /**
   * Navigate to edges in both directions.
   *
   * @param labels - Optional edge labels to match
   */
  bothE(labels?: unknown | undefined | null): Traversal
  /** Navigate from an edge to its source vertex. */
  outV(): Traversal
  /** Navigate from an edge to its target vertex. */
  inV(): Traversal
  /** Navigate from an edge to both endpoints. */
  bothV(): Traversal
  /** Navigate to the vertex that was NOT the previous step. */
  otherV(): Traversal
  /**
   * Extract property values.
   *
   * @param key - Property name to extract
   */
  values(key: string): Traversal
  /** Extract the element ID. */
  id(): Traversal
  /** Extract the element label. */
  label(): Traversal
  /** Get a map of property name to value. */
  valueMap(): Traversal
  /** Get a complete element map (id, label, and all properties). */
  elementMap(): Traversal
  /**
   * Replace each element with a constant value.
   *
   * @param value - Constant value to emit
   */
  constant(value: unknown): Traversal
  /** Flatten lists in the stream. */
  unfold(): Traversal
  /** Collect all elements into a single list. */
  fold(): Traversal
  /** Get the traversal path (history of elements visited). */
  path(): Traversal
  /**
   * Label the current step for later reference.
   *
   * @param label - Step label
   */
  as(label: string): Traversal
  /**
   * Select labeled steps from the path.
   *
   * @param labels - Step labels to select
   */
  select(labels?: unknown | undefined | null): Traversal
  /** Count the number of elements. */
  count_(): Traversal
  /** Calculate the sum of numeric values. */
  sum(): Traversal
  /** Calculate the arithmetic mean of numeric values. */
  mean(): Traversal
  /** Get the minimum value. */
  min(): Traversal
  /** Get the maximum value. */
  max(): Traversal
  /** Order by natural value (ascending). */
  orderAsc(): Traversal
  /** Order by natural value (descending). */
  orderDesc(): Traversal
  /**
   * Filter with a sub-traversal condition.
   *
   * @param traversal - Traversal that must produce results
   */
  where(traversal: Traversal): Traversal
  /**
   * Negate a filter condition.
   *
   * @param traversal - Traversal that must NOT produce results
   */
  not(traversal: Traversal): Traversal
  /**
   * Execute multiple traversals and combine results.
   *
   * @param traversals - Traversals to execute in parallel
   */
  union(traversals: Array<Traversal>): Traversal
  /**
   * Return the result of the first traversal that produces output.
   *
   * @param traversals - Traversals to try in order
   */
  coalesce(traversals: Array<Traversal>): Traversal
  /**
   * Execute traversal, but pass through original if no results.
   *
   * @param traversal - Optional traversal
   */
  optional(traversal: Traversal): Traversal
  /**
   * Execute traversal in local scope (per element).
   *
   * @param traversal - Traversal to execute locally
   */
  local(traversal: Traversal): Traversal
  /**
   * Find the shortest path (unweighted BFS) from current vertex to target.
   *
   * @param targetId - Target vertex ID
   * @returns Path as a list of vertex IDs
   */
  shortestPath(targetId: unknown): Traversal
  /**
   * Find the shortest weighted path (Dijkstra) from current vertex to target.
   *
   * @param targetId - Target vertex ID
   * @param weightProperty - Edge property to use as weight
   * @returns Path as a list of vertex IDs
   */
  shortestPathWeighted(targetId: unknown, weightProperty: string): Traversal
  /**
   * Find shortest path using A* search with a heuristic property.
   *
   * @param targetId - Target vertex ID
   * @param weightProperty - Edge property to use as weight
   * @param heuristicProperty - Vertex property with estimated distance to target
   * @returns Path as a list of vertex IDs
   */
  astar(targetId: unknown, weightProperty: string, heuristicProperty: string): Traversal
  /**
   * Find k shortest paths from current vertex to target.
   *
   * @param targetId - Target vertex ID
   * @param k - Number of paths to find
   * @param weightProperty - Edge property to use as weight
   * @returns List of paths (each path is a list of vertex IDs)
   */
  kShortestPaths(targetId: unknown, k: number, weightProperty: string): Traversal
  /**
   * Perform a breadth-first traversal from current vertex.
   *
   * @param maxDepth - Optional maximum depth
   * @returns Vertices in BFS order
   */
  bfs(maxDepth?: number | undefined | null): Traversal
  /**
   * Perform a depth-first traversal from current vertex.
   *
   * @param maxDepth - Optional maximum depth
   * @returns Vertices in DFS order
   */
  dfs(maxDepth?: number | undefined | null): Traversal
  /**
   * Find path using bidirectional BFS from current vertex to target.
   *
   * @param targetId - Target vertex ID
   * @returns Path as a list of vertex IDs
   */
  bidirectionalBfs(targetId: unknown): Traversal
  /**
   * Find path using iterative deepening DFS from current vertex to target.
   *
   * @param targetId - Target vertex ID
   * @param maxDepth - Maximum search depth
   * @returns Path as a list of vertex IDs
   */
  iddfs(targetId: unknown, maxDepth: number): Traversal
  /**
   * Extract the BM25 text relevance score from the current traverser.
   *
   * Must follow a searchText or searchTextE step.
   * @returns Relevance score as a float
   */
  textScore(): Traversal
  /**
   * Set a property on the current element.
   *
   * @param key - Property name
   * @param value - Property value
   */
  property(key: string, value: unknown): Traversal
  /** Remove the current element from the graph. */
  drop(): Traversal
  /**
   * Execute the traversal and return all results as an array.
   *
   * @returns Array of results
   */
  toList(): unknown
  /**
   * Execute and return the first result, or undefined.
   *
   * @returns First result or undefined
   */
  first(): unknown | null
  /**
   * Execute and return the next result.
   * Alias for first().
   */
  next(): unknown | null
  /**
   * Execute and return exactly one result.
   *
   * @throws If zero or more than one result
   */
  one(): unknown
  /**
   * Check if the traversal has any results.
   *
   * @returns true if at least one result exists
   */
  hasNext(): boolean
  /**
   * Execute and return the count of results.
   *
   * @returns Number of results
   */
  count(): number
  /** Iterate through all results (for side effects like drop). */
  iterate(): void
}
